{
 "title": "1.主机基础监控202207081822",
 "description": "精简优化重要指标展示。包含：CPU 内存 磁盘 IO 网络 等监控指标。https://github.com/starsliao/Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "分组名称", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node",
    "label": "IP地址",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance:.+\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "nic",
    "label": "网卡",
    "query": {
     "query": "query_result(node_network_up{interface=\"eth0\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "系统运行时间",
   "type": "stat",
   "description": "系统开机到目前的时间。",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_running_time{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_core_total{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "进程队列长度",
   "type": "stat",
   "description": "runq-sz：运行队列的长度（等待运行的进程数）。\n\nplist-sz：进程列表中进程（processes）和线程（threads）的数量。",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_runq_sz", "legendFormat": "runq-sz" },
    { "expr": "process_plist_sz", "legendFormat": "plist-sz" }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "100 - cpu_seconds_idle" }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((memory_MemTotal_kb{instance=~\"$node\"} - memory_MemFree_kb{instance=~\"$node\"} - memory_Buffers_kb{instance=~\"$node\"} - memory_Cached_kb{instance=~\"$node\"}) / (memory_MemTotal_kb{instance=~\"$node\"} )) * 100"
    }
   ]
  },
  {
   "title": "根分区使用率",
   "type": "gauge",
   "description": "根分区使用率",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used{instance=~'$node',fstype=~\"ext4|xfs\"} / disk_total{instance=~'$node',fstype=~\"ext4|xfs\"}"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_MemTotal_kb{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用状态",
   "type": "stat",
   "description": "%system：内核空间占用CPU百分比。\n\n%user：用户空间占用CPU百分比。\n\n%idle：空闲的CPU百分比。\n\n%iowait：CPU等待IO数据的百分比。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_seconds_system", "legendFormat": "System" },
    { "expr": "cpu_seconds_user", "legendFormat": "User" },
    { "expr": "cpu_seconds_idle", "legendFormat": "Idle" },
    { "expr": "cpu_seconds_iowait", "legendFormat": "Iowait" }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "description": "系统负载表示一段时间内正在使用和等待使用CPU的平均任务数。与CPU的核数有关。\n\n例如：CPU核数为1，负载为1，表示系统处于满载状态。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load1{instance=~\"$node\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "load5{instance=~\"$node\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "load15{instance=~\"$node\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memory_MemTotal_kb{instance=~\"$node\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "memory_MemTotal_kb{instance=~\"$node\"} - (memory_Cached_kb{instance=~\"$node\"} + memory_Buffers_kb{instance=~\"$node\"} + memory_MemFree_kb{instance=~\"$node\"})",
     "legendFormat": "已用"
    },
    {
     "expr": "memory_MemAvailable_kb{instance=~\"$node\"}",
     "legendFormat": "可用"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "disk_total{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint=~\"/|/home|/data\"} - disk_avail{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint=~\"/|/home|/data\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_total{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint=~\"/|/home|/data\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_used{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint=~\"/|/home|/data\"} / disk_total{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint=~\"/|/home|/data\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "网络进出带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "network_receive_bytes_sec{instance=~'$node',device=~'eth0'}",
     "legendFormat": "{{device}}_进带宽(Receive)"
    },
    {
     "expr": "network_transmit_bytes_sec{instance=~'$node',device=~'eth0'}",
     "legendFormat": "{{device}}_出带宽(Transmit)"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netstat_tcp_ESTAB{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "netstat_tcp_LISTEN{instance=~'$node'}",
     "legendFormat": "LISTEN"
    },
    {
     "expr": "netstat_tcp_SYNRECV{instance=~'$node'}",
     "legendFormat": "SYN-RECV"
    },
    {
     "expr": "netstat_tcp_FINWAIT1{instance=~'$node'}",
     "legendFormat": "FIN-WAIT-1"
    },
    {
     "expr": "netstat_tcp_FINWAIT2{instance=~'$node'}",
     "legendFormat": "FIN-WAIT-2"
    },
    {
     "expr": "netstat_tcp_TIMEWAIT{instance=~'$node'}",
     "legendFormat": "TIME-WAIT"
    },
    {
     "expr": "netstat_tcp_LASTACK{instance=~'$node'}",
     "legendFormat": "LAST-ACK"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "IOPS（Input/Output Per Second）：指每秒 I/O 请求的数量。\n\nReads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "disk_vda_iops_read{instance=~\"$node\",device=~\"vda\"}",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "disk_vda_iops_write{instance=~\"$node\",device=~\"vda\"}",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘吞吐量（Throughput）",
   "type": "graph",
   "description": "磁盘吞吐量（Throughput）：每秒 I/O 请求的大小。\n\nRead bytes 每个磁盘分区每秒读取的字节数。\n\nWritten bytes 每个磁盘分区每秒写入的字节数。\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "KBs", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "disk_vda_read_KB{instance=~\"$node\",device=~\"vda\"}",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "disk_vda_write_KB{instance=~\"$node\",device=~\"vda\"}",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘IO利用率（Utilization）",
   "type": "graph",
   "description": "利用率（Utilization）：磁盘处理 I/O 的时间百分比。过度使用（如超过 80%）通常意味着磁盘 I/O 存在性能瓶颈。",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "disk_vda_Utilization{device=~\"vda\"}",
     "legendFormat": "{{device}}_每秒I/O操作_%"
    }
   ]
  },
  {
   "title": "磁盘IO读写响应时间（Response time）",
   "type": "graph",
   "description": "响应时间（Response time）：指发送 I/O 请求和接收响应之间的间隔时间。（参考：小于100ms）",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "读取（-）/  写入（+）" }
   ],
   "targets": [
    {
     "expr": "disk_vda_r_await{device=~\"vda\"}",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "disk_vda_w_await{device=~\"vda\"}",
     "legendFormat": "{{device}}_写入"
    }
   ]
  }
 ]
}