apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-cluster-pv
  labels:
    type: glusterfs
spec:
  storageClassName: glusterfs-volume
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle  
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "k8s-volume"
    readOnly: false
