apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-cluster-pvc
spec:
  storageClassName: glusterfs-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
