apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-heketi
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
allowVolumeExpansion: true
parameters:
  resturl: "http://10.101.86.169:8080"
  restauthenabled: "false"
  volumetype: "replicate:3"

