apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-demo-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 20480Mi
          limits:
            memory: 20480Mi

