apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
- addresses:
  - ip: 10.159.238.40
  - ip: 10.159.238.41
  - ip: 10.159.238.42
  ports:
  - port: 49152
    protocol: TCP
